// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var Midway;

  Midway = (function() {
    function Midway() {
      this.centerHorizontalItems = $('.midway-horizontal');
      this.centerVerticalItems = $('.midway-vertical');
      this.horizontalCss = {
        display: 'inline',
        position: 'absolute',
        left: '50%'
      };
      this.verticalCss = {
        display: 'inline',
        position: 'absolute',
        top: '50%'
      };
      this.update();
    }

    Midway.prototype.update = function() {
      this.centerHorizontalItems.each(function() {
        return $(this).css('marginLeft', -$(this).outerWidth() / 2);
      }).css(this.horizontalCss);
      return this.centerVerticalItems.each(function() {
        return $(this).css('marginTop', -$(this).outerHeight() / 2);
      }).css(this.verticalCss);
    };

    return Midway;

  })();

  $(document).ready(function() {
    var _midwayAlignment;
    _midwayAlignment = new Midway();
    return $(window).on('load, resize', _midwayAlignment.update);
  });

}).call(this);

/*
//@ sourceMappingURL=Midway.map
*/
